apiVersion: v1
kind: Service
metadata:
  name: weight-app-service
  namespace: app
spec:
  selector:
    app: weight-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080